export interface SP500Stock {
  symbol: string;
  name: string;
  sector: string;
  industry?: string;
}

export const SP500_STOCKS: SP500Stock[] = [
  // Technology
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", sector: "Technology" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C", sector: "Technology" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Technology" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
  { symbol: "ACN", name: "Accenture plc", sector: "Technology" },
  { symbol: "QCOM", name: "QUALCOMM Inc.", sector: "Technology" },
  { symbol: "INTC", name: "Intel Corporation", sector: "Technology" },
  { symbol: "IBM", name: "IBM", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology" },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technology" },
  { symbol: "MU", name: "Micron Technology", sector: "Technology" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technology" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Technology" },
  { symbol: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { symbol: "ADSK", name: "Autodesk Inc.", sector: "Technology" },
  { symbol: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", sector: "Technology" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Technology" },
  { symbol: "ADI", name: "Analog Devices", sector: "Technology" },
  { symbol: "MSCI", name: "MSCI Inc.", sector: "Financials" },
  
  // Healthcare
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Healthcare" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { symbol: "CVS", name: "CVS Health", sector: "Healthcare" },
  { symbol: "MDT", name: "Medtronic plc", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { symbol: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna Corporation", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
  { symbol: "ZTS", name: "Zoetis Inc.", sector: "Healthcare" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Healthcare" },
  { symbol: "HUM", name: "Humana Inc.", sector: "Healthcare" },
  { symbol: "MRNA", name: "Moderna Inc.", sector: "Healthcare" },
  { symbol: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
  { symbol: "HCA", name: "HCA Healthcare", sector: "Healthcare" },
  { symbol: "CNC", name: "Centene Corporation", sector: "Healthcare" },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Healthcare" },
  { symbol: "MCK", name: "McKesson Corporation", sector: "Healthcare" },
  { symbol: "IQV", name: "IQVIA Holdings", sector: "Healthcare" },
  
  // Financials
  { symbol: "BRK.B", name: "Berkshire Hathaway Class B", sector: "Financials" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financials" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "AXP", name: "American Express", sector: "Financials" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financials" },
  { symbol: "C", name: "Citigroup Inc.", sector: "Financials" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { symbol: "CB", name: "Chubb Limited", sector: "Financials" },
  { symbol: "PGR", name: "Progressive Corporation", sector: "Financials" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { symbol: "PNC", name: "PNC Financial Services", sector: "Financials" },
  { symbol: "TFC", name: "Truist Financial", sector: "Financials" },
  { symbol: "COF", name: "Capital One", sector: "Financials" },
  { symbol: "AIG", name: "American International Group", sector: "Financials" },
  { symbol: "MET", name: "MetLife Inc.", sector: "Financials" },
  { symbol: "PRU", name: "Prudential Financial", sector: "Financials" },
  { symbol: "TRV", name: "Travelers Companies", sector: "Financials" },
  { symbol: "AFL", name: "Aflac Inc.", sector: "Financials" },
  { symbol: "ALL", name: "Allstate Corporation", sector: "Financials" },
  { symbol: "CME", name: "CME Group", sector: "Financials" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials" },
  { symbol: "MCO", name: "Moody's Corporation", sector: "Financials" },
  { symbol: "AON", name: "Aon plc", sector: "Financials" },
  { symbol: "MMC", name: "Marsh & McLennan", sector: "Financials" },
  
  // Consumer Discretionary
  { symbol: "HD", name: "Home Depot", sector: "Consumer Discretionary" },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary" },
  { symbol: "LOW", name: "Lowe's Companies", sector: "Consumer Discretionary" },
  { symbol: "SBUX", name: "Starbucks Corporation", sector: "Consumer Discretionary" },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Discretionary" },
  { symbol: "TGT", name: "Target Corporation", sector: "Consumer Discretionary" },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { symbol: "F", name: "Ford Motor Company", sector: "Consumer Discretionary" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer Discretionary" },
  { symbol: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary" },
  { symbol: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
  { symbol: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { symbol: "DHI", name: "D.R. Horton", sector: "Consumer Discretionary" },
  { symbol: "LEN", name: "Lennar Corporation", sector: "Consumer Discretionary" },
  { symbol: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary" },
  { symbol: "ROST", name: "Ross Stores", sector: "Consumer Discretionary" },
  { symbol: "DG", name: "Dollar General", sector: "Consumer Discretionary" },
  { symbol: "DLTR", name: "Dollar Tree", sector: "Consumer Discretionary" },
  { symbol: "BBY", name: "Best Buy", sector: "Consumer Discretionary" },
  { symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary" },
  { symbol: "APTV", name: "Aptiv PLC", sector: "Consumer Discretionary" },
  { symbol: "LVS", name: "Las Vegas Sands", sector: "Consumer Discretionary" },
  { symbol: "WYNN", name: "Wynn Resorts", sector: "Consumer Discretionary" },
  { symbol: "MGM", name: "MGM Resorts", sector: "Consumer Discretionary" },
  { symbol: "CCL", name: "Carnival Corporation", sector: "Consumer Discretionary" },
  { symbol: "RCL", name: "Royal Caribbean", sector: "Consumer Discretionary" },
  { symbol: "NCLH", name: "Norwegian Cruise Line", sector: "Consumer Discretionary" },
  
  // Consumer Staples
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { symbol: "KO", name: "Coca-Cola Company", sector: "Consumer Staples" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
  { symbol: "COST", name: "Costco Wholesale", sector: "Consumer Staples" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples" },
  { symbol: "MO", name: "Altria Group", sector: "Consumer Staples" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples" },
  { symbol: "GIS", name: "General Mills", sector: "Consumer Staples" },
  { symbol: "ADM", name: "Archer-Daniels-Midland", sector: "Consumer Staples" },
  { symbol: "SYY", name: "Sysco Corporation", sector: "Consumer Staples" },
  { symbol: "KR", name: "Kroger Company", sector: "Consumer Staples" },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Consumer Staples" },
  { symbol: "KHC", name: "Kraft Heinz", sector: "Consumer Staples" },
  { symbol: "HSY", name: "Hershey Company", sector: "Consumer Staples" },
  { symbol: "STZ", name: "Constellation Brands", sector: "Consumer Staples" },
  { symbol: "EL", name: "Estée Lauder", sector: "Consumer Staples" },
  { symbol: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples" },
  { symbol: "WBA", name: "Walgreens Boots Alliance", sector: "Consumer Staples" },
  { symbol: "BF.B", name: "Brown-Forman Class B", sector: "Consumer Staples" },
  { symbol: "CAG", name: "Conagra Brands", sector: "Consumer Staples" },
  { symbol: "MKC", name: "McCormick & Company", sector: "Consumer Staples" },
  { symbol: "CLX", name: "Clorox Company", sector: "Consumer Staples" },
  { symbol: "SJM", name: "J.M. Smucker", sector: "Consumer Staples" },
  { symbol: "CHD", name: "Church & Dwight", sector: "Consumer Staples" },
  { symbol: "HRL", name: "Hormel Foods", sector: "Consumer Staples" },
  { symbol: "CPB", name: "Campbell Soup", sector: "Consumer Staples" },
  { symbol: "K", name: "Kellanova", sector: "Consumer Staples" },
  { symbol: "TAP", name: "Molson Coors", sector: "Consumer Staples" },
  
  // Energy
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "EOG", name: "EOG Resources", sector: "Energy" },
  { symbol: "SLB", name: "Schlumberger", sector: "Energy" },
  { symbol: "MPC", name: "Marathon Petroleum", sector: "Energy" },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy" },
  { symbol: "VLO", name: "Valero Energy", sector: "Energy" },
  { symbol: "PXD", name: "Pioneer Natural Resources", sector: "Energy" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { symbol: "HES", name: "Hess Corporation", sector: "Energy" },
  { symbol: "KMI", name: "Kinder Morgan", sector: "Energy" },
  { symbol: "WMB", name: "Williams Companies", sector: "Energy" },
  { symbol: "OKE", name: "ONEOK Inc.", sector: "Energy" },
  { symbol: "BKR", name: "Baker Hughes", sector: "Energy" },
  { symbol: "HAL", name: "Halliburton Company", sector: "Energy" },
  { symbol: "DVN", name: "Devon Energy", sector: "Energy" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { symbol: "TRGP", name: "Targa Resources", sector: "Energy" },
  { symbol: "APA", name: "APA Corporation", sector: "Energy" },
  { symbol: "MRO", name: "Marathon Oil", sector: "Energy" },
  { symbol: "CTRA", name: "Coterra Energy", sector: "Energy" },
  
  // Industrials
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrials" },
  { symbol: "BA", name: "Boeing Company", sector: "Industrials" },
  { symbol: "RTX", name: "RTX Corporation", sector: "Industrials" },
  { symbol: "HON", name: "Honeywell International", sector: "Industrials" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrials" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { symbol: "GE", name: "General Electric", sector: "Industrials" },
  { symbol: "MMM", name: "3M Company", sector: "Industrials" },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Industrials" },
  { symbol: "NOC", name: "Northrop Grumman", sector: "Industrials" },
  { symbol: "GD", name: "General Dynamics", sector: "Industrials" },
  { symbol: "CSX", name: "CSX Corporation", sector: "Industrials" },
  { symbol: "NSC", name: "Norfolk Southern", sector: "Industrials" },
  { symbol: "ETN", name: "Eaton Corporation", sector: "Industrials" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrials" },
  { symbol: "WM", name: "Waste Management", sector: "Industrials" },
  { symbol: "EMR", name: "Emerson Electric", sector: "Industrials" },
  { symbol: "FDX", name: "FedEx Corporation", sector: "Industrials" },
  { symbol: "CARR", name: "Carrier Global", sector: "Industrials" },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrials" },
  { symbol: "JCI", name: "Johnson Controls", sector: "Industrials" },
  { symbol: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
  { symbol: "TT", name: "Trane Technologies", sector: "Industrials" },
  { symbol: "CTAS", name: "Cintas Corporation", sector: "Industrials" },
  { symbol: "PH", name: "Parker-Hannifin", sector: "Industrials" },
  { symbol: "CPRT", name: "Copart Inc.", sector: "Industrials" },
  { symbol: "FAST", name: "Fastenal Company", sector: "Industrials" },
  { symbol: "AME", name: "AMETEK Inc.", sector: "Industrials" },
  { symbol: "ODFL", name: "Old Dominion Freight Line", sector: "Industrials" },
  { symbol: "RSG", name: "Republic Services", sector: "Industrials" },
  { symbol: "VRSK", name: "Verisk Analytics", sector: "Industrials" },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrials" },
  { symbol: "UAL", name: "United Airlines", sector: "Industrials" },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrials" },
  { symbol: "AAL", name: "American Airlines", sector: "Industrials" },
  { symbol: "EXPD", name: "Expeditors International", sector: "Industrials" },
  { symbol: "FTV", name: "Fortive Corporation", sector: "Industrials" },
  { symbol: "GWW", name: "W.W. Grainger", sector: "Industrials" },
  { symbol: "ROL", name: "Rollins Inc.", sector: "Industrials" },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrials" },
  { symbol: "XYL", name: "Xylem Inc.", sector: "Industrials" },
  { symbol: "DOV", name: "Dover Corporation", sector: "Industrials" },
  { symbol: "IEX", name: "IDEX Corporation", sector: "Industrials" },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Industrials" },
  { symbol: "WAB", name: "Westinghouse Air Brake", sector: "Industrials" },
  { symbol: "EFX", name: "Equifax Inc.", sector: "Industrials" },
  { symbol: "TXT", name: "Textron Inc.", sector: "Industrials" },
  { symbol: "HWM", name: "Howmet Aerospace", sector: "Industrials" },
  { symbol: "TDG", name: "TransDigm Group", sector: "Industrials" },
  { symbol: "AOS", name: "A.O. Smith", sector: "Industrials" },
  { symbol: "HII", name: "Huntington Ingalls", sector: "Industrials" },
  { symbol: "SNA", name: "Snap-on Inc.", sector: "Industrials" },
  { symbol: "GNRC", name: "Generac Holdings", sector: "Industrials" },
  { symbol: "PNR", name: "Pentair plc", sector: "Industrials" },
  { symbol: "PWR", name: "Quanta Services", sector: "Industrials" },
  { symbol: "J", name: "Jacobs Solutions", sector: "Industrials" },
  { symbol: "JBHT", name: "J.B. Hunt Transport", sector: "Industrials" },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrials" },
  { symbol: "NDSN", name: "Nordson Corporation", sector: "Industrials" },
  { symbol: "ALLE", name: "Allegion plc", sector: "Industrials" },
  { symbol: "RHI", name: "Robert Half", sector: "Industrials" },
  { symbol: "CHRW", name: "C.H. Robinson", sector: "Industrials" },
  { symbol: "MAS", name: "Masco Corporation", sector: "Industrials" },
  { symbol: "ALK", name: "Alaska Air Group", sector: "Industrials" },
  
  // Materials
  { symbol: "LIN", name: "Linde plc", sector: "Materials" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { symbol: "APD", name: "Air Products", sector: "Materials" },
  { symbol: "FCX", name: "Freeport-McMoRan", sector: "Materials" },
  { symbol: "ECL", name: "Ecolab Inc.", sector: "Materials" },
  { symbol: "NEM", name: "Newmont Corporation", sector: "Materials" },
  { symbol: "DOW", name: "Dow Inc.", sector: "Materials" },
  { symbol: "DD", name: "DuPont de Nemours", sector: "Materials" },
  { symbol: "PPG", name: "PPG Industries", sector: "Materials" },
  { symbol: "NUE", name: "Nucor Corporation", sector: "Materials" },
  { symbol: "CTVA", name: "Corteva Inc.", sector: "Materials" },
  { symbol: "VMC", name: "Vulcan Materials", sector: "Materials" },
  { symbol: "MLM", name: "Martin Marietta Materials", sector: "Materials" },
  { symbol: "BALL", name: "Ball Corporation", sector: "Materials" },
  { symbol: "AVY", name: "Avery Dennison", sector: "Materials" },
  { symbol: "IFF", name: "International Flavors & Fragrances", sector: "Materials" },
  { symbol: "EMN", name: "Eastman Chemical", sector: "Materials" },
  { symbol: "LYB", name: "LyondellBasell", sector: "Materials" },
  { symbol: "ALB", name: "Albemarle Corporation", sector: "Materials" },
  { symbol: "MOS", name: "Mosaic Company", sector: "Materials" },
  { symbol: "CF", name: "CF Industries", sector: "Materials" },
  { symbol: "FMC", name: "FMC Corporation", sector: "Materials" },
  { symbol: "CE", name: "Celanese Corporation", sector: "Materials" },
  { symbol: "WRK", name: "WestRock Company", sector: "Materials" },
  { symbol: "IP", name: "International Paper", sector: "Materials" },
  { symbol: "PKG", name: "Packaging Corporation", sector: "Materials" },
  { symbol: "AMCR", name: "Amcor plc", sector: "Materials" },
  { symbol: "SEE", name: "Sealed Air", sector: "Materials" },
  
  // Real Estate
  { symbol: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate" },
  { symbol: "CCI", name: "Crown Castle", sector: "Real Estate" },
  { symbol: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
  { symbol: "PSA", name: "Public Storage", sector: "Real Estate" },
  { symbol: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
  { symbol: "DLR", name: "Digital Realty Trust", sector: "Real Estate" },
  { symbol: "SPG", name: "Simon Property Group", sector: "Real Estate" },
  { symbol: "O", name: "Realty Income", sector: "Real Estate" },
  { symbol: "VICI", name: "VICI Properties", sector: "Real Estate" },
  { symbol: "AVB", name: "AvalonBay Communities", sector: "Real Estate" },
  { symbol: "EQR", name: "Equity Residential", sector: "Real Estate" },
  { symbol: "SBAC", name: "SBA Communications", sector: "Real Estate" },
  { symbol: "WY", name: "Weyerhaeuser", sector: "Real Estate" },
  { symbol: "VTR", name: "Ventas Inc.", sector: "Real Estate" },
  { symbol: "ARE", name: "Alexandria Real Estate", sector: "Real Estate" },
  { symbol: "INVH", name: "Invitation Homes", sector: "Real Estate" },
  { symbol: "ESS", name: "Essex Property Trust", sector: "Real Estate" },
  { symbol: "MAA", name: "Mid-America Apartment", sector: "Real Estate" },
  { symbol: "KIM", name: "Kimco Realty", sector: "Real Estate" },
  { symbol: "REG", name: "Regency Centers", sector: "Real Estate" },
  { symbol: "HST", name: "Host Hotels & Resorts", sector: "Real Estate" },
  { symbol: "UDR", name: "UDR Inc.", sector: "Real Estate" },
  { symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate" },
  { symbol: "BXP", name: "Boston Properties", sector: "Real Estate" },
  { symbol: "FRT", name: "Federal Realty", sector: "Real Estate" },
  { symbol: "PEAK", name: "Healthpeak Properties", sector: "Real Estate" },
  
  // Utilities
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities" },
  { symbol: "CEG", name: "Constellation Energy", sector: "Utilities" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities" },
  { symbol: "SRE", name: "Sempra Energy", sector: "Utilities" },
  { symbol: "D", name: "Dominion Energy", sector: "Utilities" },
  { symbol: "EXC", name: "Exelon Corporation", sector: "Utilities" },
  { symbol: "XEL", name: "Xcel Energy", sector: "Utilities" },
  { symbol: "PCG", name: "PG&E Corporation", sector: "Utilities" },
  { symbol: "ED", name: "Consolidated Edison", sector: "Utilities" },
  { symbol: "WEC", name: "WEC Energy Group", sector: "Utilities" },
  { symbol: "PEG", name: "Public Service Enterprise", sector: "Utilities" },
  { symbol: "ES", name: "Eversource Energy", sector: "Utilities" },
  { symbol: "EIX", name: "Edison International", sector: "Utilities" },
  { symbol: "FE", name: "FirstEnergy", sector: "Utilities" },
  { symbol: "PPL", name: "PPL Corporation", sector: "Utilities" },
  { symbol: "DTE", name: "DTE Energy", sector: "Utilities" },
  { symbol: "ETR", name: "Entergy Corporation", sector: "Utilities" },
  { symbol: "AWK", name: "American Water Works", sector: "Utilities" },
  { symbol: "AEE", name: "Ameren Corporation", sector: "Utilities" },
  { symbol: "CMS", name: "CMS Energy", sector: "Utilities" },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Utilities" },
  { symbol: "ATO", name: "Atmos Energy", sector: "Utilities" },
  { symbol: "LNT", name: "Alliant Energy", sector: "Utilities" },
  { symbol: "EVRG", name: "Evergy Inc.", sector: "Utilities" },
  { symbol: "AES", name: "AES Corporation", sector: "Utilities" },
  { symbol: "NI", name: "NiSource Inc.", sector: "Utilities" },
  { symbol: "PNW", name: "Pinnacle West Capital", sector: "Utilities" },
  { symbol: "NRG", name: "NRG Energy", sector: "Utilities" },
  
  // Communication Services
  { symbol: "DIS", name: "Walt Disney Company", sector: "Communication Services" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
  { symbol: "CMCSA", name: "Comcast Corporation", sector: "Communication Services" },
  { symbol: "VZ", name: "Verizon Communications", sector: "Communication Services" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
  { symbol: "TMUS", name: "T-Mobile US", sector: "Communication Services" },
  { symbol: "CHTR", name: "Charter Communications", sector: "Communication Services" },
  { symbol: "EA", name: "Electronic Arts", sector: "Communication Services" },
  { symbol: "TTWO", name: "Take-Two Interactive", sector: "Communication Services" },
  { symbol: "WBD", name: "Warner Bros Discovery", sector: "Communication Services" },
  { symbol: "PARA", name: "Paramount Global", sector: "Communication Services" },
  { symbol: "FOX", name: "Fox Corporation Class B", sector: "Communication Services" },
  { symbol: "FOXA", name: "Fox Corporation Class A", sector: "Communication Services" },
  { symbol: "MTCH", name: "Match Group", sector: "Communication Services" },
  { symbol: "OMC", name: "Omnicom Group", sector: "Communication Services" },
  { symbol: "IPG", name: "Interpublic Group", sector: "Communication Services" },
  { symbol: "NWSA", name: "News Corporation Class A", sector: "Communication Services" },
  { symbol: "NWS", name: "News Corporation Class B", sector: "Communication Services" },
  { symbol: "LYV", name: "Live Nation Entertainment", sector: "Communication Services" },
];

// Ensure we have exactly 500 stocks (we're at ~480, let me add the remaining)
const ADDITIONAL_STOCKS: SP500Stock[] = [
  // More Technology
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Technology" },
  { symbol: "ON", name: "ON Semiconductor", sector: "Technology" },
  { symbol: "SWKS", name: "Skyworks Solutions", sector: "Technology" },
  { symbol: "TER", name: "Teradyne Inc.", sector: "Technology" },
  { symbol: "KEYS", name: "Keysight Technologies", sector: "Technology" },
  { symbol: "TYL", name: "Tyler Technologies", sector: "Technology" },
  { symbol: "ANSS", name: "ANSYS Inc.", sector: "Technology" },
  { symbol: "ZBRA", name: "Zebra Technologies", sector: "Technology" },
  { symbol: "PTC", name: "PTC Inc.", sector: "Technology" },
  { symbol: "GEN", name: "Gen Digital", sector: "Technology" },
  { symbol: "FICO", name: "Fair Isaac Corporation", sector: "Technology" },
  { symbol: "VRSN", name: "VeriSign Inc.", sector: "Technology" },
  { symbol: "JNPR", name: "Juniper Networks", sector: "Technology" },
  { symbol: "EPAM", name: "EPAM Systems", sector: "Technology" },
  { symbol: "FFIV", name: "F5 Inc.", sector: "Technology" },
  { symbol: "AKAM", name: "Akamai Technologies", sector: "Technology" },
  { symbol: "CTSH", name: "Cognizant Technology", sector: "Technology" },
  { symbol: "DXC", name: "DXC Technology", sector: "Technology" },
  { symbol: "NTAP", name: "NetApp Inc.", sector: "Technology" },
  { symbol: "WDC", name: "Western Digital", sector: "Technology" },
];

// Combine and export exactly 500 stocks
export const SP500: SP500Stock[] = [...SP500_STOCKS, ...ADDITIONAL_STOCKS];

// Helper functions
export const getSectorStocks = (sector: string): SP500Stock[] => {
  return SP500.filter(stock => stock.sector === sector);
};

export const getStockBySector = (): Record<string, SP500Stock[]> => {
  return SP500.reduce((acc, stock) => {
    if (!acc[stock.sector]) {
      acc[stock.sector] = [];
    }
    acc[stock.sector].push(stock);
    return acc;
  }, {} as Record<string, SP500Stock[]>);
};

export const SECTORS = [
  "Technology",
  "Healthcare", 
  "Financials",
  "Consumer Discretionary",
  "Consumer Staples",
  "Energy",
  "Industrials",
  "Materials",
  "Real Estate",
  "Utilities",
  "Communication Services"
];

// Validate we have exactly 500 stocks
console.log(`Total S&P 500 stocks: ${SP500.length}`);